### ISSUE TITLE
stack-repo Task: Allow naming of git branch created

### ISSUE THREAD

**Issue by louisfischer** [eleven-financial/stack-board-extension#11]
Thank you developing a great plugin for Azure DevOps. 

Would it be possible to allow the customization of the branch name being created?
Instead of defaulting to develop, allow a Variable to be set. If no variable is present, default to develop.

https://github.com/eleven-financial/stack-board-extension/blob/d00a57911d49fdca054406cc635a23b09f59be15/tasks/stack-board-repos/stackboardrepos.ts#L134
https://github.com/eleven-financial/stack-board-extension/blob/d00a57911d49fdca054406cc635a23b09f59be15/tasks/stack-board-repos/stackboardrepos.ts#L137

**Comment by louisfischer** [comment]
If this is possible, I would be more than happy to submit a PR for the requested change

**Comment by renatodans** [comment]
Hi Louis, sure.
We will very happy with your contribution.

This variable (branch) can include in the Settings - Template Catalog screen, like "Replace Key".
Thanks!

**Comment by louisfischer** [comment]
@renatodans Thank you. I will create a PR for the changes. Also what version and arch of Node are you using to compile the project. I tried with several different ones and kept getting an error just doing an npm install in the front and task folders

**Comment by renatodans** [comment]
Hi @louisfischer, 

Node version I am using is - v14.16.0
But is need to run "npm install" into each folder

- /front
- /tasks/stack-board-repos
- /tasks/stack-board-replaces

Could you test, please?
